[database.mongo]
dataSource = "mongodb+srv://test:1111@super-mongo.f9qbhma.mongodb.net/?retryWrites=true&w=majority"
db = "event-catch-module"
nftCollection = "nftCollection"
nft = "nft"
tx = "tx"

[node]
uri = "https://polygon-mumbai.infura.io/v3/cea0d8acc3e4470dab059c41a00c6e28"